### ISSUE TITLE
Update pull request template to nudge users to update Sandbox updates banner

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-docs#117]
The new DEA Changelog is fantastic, and provides a great place for us to document changes and updates across DEA. However, we do run the risk of forgetting to also update the DEA Sandbox "Updates" banner, which is the other high profile location where we share updates with our users:

![image](https://github.com/GeoscienceAustralia/dea-docs/assets/17680388/4da26efc-ac8b-4379-aea1-005d8a7f3df5)

I would like to propose that we add two additional checklist items to the current pull request template, to encourage (but not force) users to keep our update sections up to date:

> * [ ] If required, update the [DEA Tech Alerts and Changelog page](https://github.com/GeoscienceAustralia/dea-docs/blob/main/docs/tech-alerts-changelog/_tech_alerts_changelog.md)
> * [ ] If required, update the [DEA Sandbox Updates banner](https://bitbucket.org/geoscienceaustralia/datakube-apps/src/64c28bbf3d0e019d8940547a22f78b9bfd58d739/clusters/dea-sandbox/sandbox.yaml#lines-22:41)

**Comment by benji-glitsos-ga** [comment]
This task is done so I'm closing the issue.
