### ISSUE TITLE
update VDI and NCI info to refer to OOD service

### ISSUE THREAD

**Issue by BexDunn** [GeoscienceAustralia/dea-docs#18]
I believe NCI is moving from Strudel + TurboVNC to OOD:

https://opus.nci.org.au/display/OOD/OOD+FAQ

**Comment by BexDunn** [comment]
as at 26/07/2021: 

Transition to OOD for existing VDI users:
For users of the existing VDI, you will see that both the VDI and JupyterLab apps within OOD use the same software and home directory as the old VDI, so you can move across without any extra steps.
We strongly encourage existing VDI users to move to OOD as soon as possible. No new users will be started on the old VDI service.

Old VDI Service Security Updates:
As part of a recent security review, we are removing some legacy security protocols on Thursday, 29th July. The impact of this will be that some users may not be able to use their existing Strudel to connect to the old VDI. We recommend that you start using the OOD VDI app instead which does not have this issue. Alternatively, as an interim step you could upgrade to the latest Strudel client.

End of Life and Decommissioning of old VDI
We note that after approx. 1 month, we will be moving to decommission the old Strudel-based VDI completely. The old hardware has been progressively hard to maintain and is out of maintenance, and the functionality is now better supported within the OOD.

**Comment by CEKrause** [comment]
Superseded by the new system
