### ISSUE TITLE
Copy DE Africa explorer documentation for DEA

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/dea-docs#59]

**Comment by CEKrause** [comment]
https://docs.digitalearthafrica.org/en/latest/platform_tools/explorer_guide.html

**Comment by CEKrause** [comment]
https://github.com/GeoscienceAustralia/dea-docs/pull/64

**Comment by benji-glitsos-ga** [comment]
Closing this because Claire completed this task.

https://docs.dea.ga.gov.au/guides/setup/explorer_guide/
