### ISSUE TITLE
No mention of our DEA Support Email address

### ISSUE THREAD

**Issue by omad** [GeoscienceAustralia/dea-docs#60]
earth.observation@ga.gov.au is listed at https://www.dea.ga.gov.au/contact , but nowhere in the user guide.

**Comment by benji-glitsos-ga** [comment]
In the footer, there is now a Contact us link that goes to that URL that contains the email address.

![ksnip_20240207-155041](https://github.com/GeoscienceAustralia/dea-docs/assets/144193171/81dd1bc9-33f4-416f-8a1b-963d37f3e8d3)

I can see the email address is featured on a few pages.

**Do we need this email address to feature more prominently?**

```
guides/setup/Sandbox/sandbox.rst
154:You can view the current system status `here`_. If you are experiencing an issue with the Sandbox that isn't identified on the status page, please sub [... 1 more match]
195:You can close your account at any time by emailing the DEA team (`earth.observation@ga.gov.au`_).
201:.. _earth.observation@ga.gov.au: mailto:earth.observation@ga.gov.au

guides/setup/NCI/account.rst
42:.. _DEA Helpdesk: mailto:earth.observation@ga.gov.au

data/product/dea-waterbodies-landsat/_faqs.md
148:Contact us at <a href="mailto:Earth.Observation@ga.gov.au">Earth.Observation@ga.gov.au</a>

data/product/dea-waterbodies-landsat/_access.md
39:If you need more help, contact earth.observation@ga.gov.au. 

data/product/dea-hotspots/_details.md
20:  * To apply for access, email earth.observation@ga.gov.au
```

**Comment by robbibt** [comment]
I reckon this is fine for now! I suspect Damien's comment pre-dated Knowledge Hub.

**Comment by benji-glitsos-ga** [comment]
Ok I'll close this unless @omad wants to reopen it.

**Comment by omad** [comment]
That **Contact** link in the footer looks good to me Benji!

I'd probably make it not open in a new tab, but happy to close this ticket.

Thanks

**Comment by benji-glitsos-ga** [comment]
Thanks Damien. There is a script on the site that makes all external links (different domain name) open in a new tab. That is causing it. We could consider changing the rule that determines which links open in a new tab? I'll have a think.

**Comment by omad** [comment]
I'm generally against forcing things to open in a new tab at all.

But especially in this case, I think we want the DEA sites to feel coherent and that definitely doesn't.

**Comment by benji-glitsos-ga** [comment]
For consistency with the GA and DEA websites, I'm now making the external links open in the same tab. https://github.com/GeoscienceAustralia/dea-docs/pull/102
